'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const stats = require('../stats.js');
const { comparisonTolerance, atOrBelow, extremeBy, longestRun, median, quantile, spendingProfile, resolveNeed, needProfile } = stats;
const profile = (realSpending, extra = {}) => spendingProfile({ realSpending, baseline: 40, horizon: realSpending.length, failed: false, partial: false, startYear: 2000, ...extra });
const close = (actual, expected) => assert.ok(Math.abs(actual - expected) < 1e-12, `${actual} != ${expected}`);

test('stats exposes only its frozen namespace in browser and CommonJS', () => {
  assert.ok(Object.isFrozen(stats));
  const context = vm.createContext({});
  vm.runInContext(fs.readFileSync(require.resolve('../stats.js'), 'utf8'), context);
  assert.deepEqual(Object.keys(context), ['MarketAtlasStats']);
  assert.ok(Object.isFrozen(context.MarketAtlasStats));
  assert.equal(globalThis.MarketAtlasStats, stats);
});
test('tolerance comparisons retain the first finite extreme and meaningful differences', () => {
  assert.equal(comparisonTolerance(2, -3), Number.EPSILON * 8 * 3);
  assert.equal(atOrBelow(22631.650335181042, 22631.650335181035), true);
  assert.equal(atOrBelow(.66, .65), false);
  assert.equal(atOrBelow(22631.66, 22631.65), false);
  assert.equal(extremeBy([3, 1.0000000000000002, 1, 2], v => v, 'min').index, 1);
  assert.equal(extremeBy([1, 5, 5], v => v, 'max').index, 1);
  assert.deepEqual(extremeBy([{ v: NaN }, { v: 3 }], x => x.v, 'min'), { item: { v: 3 }, index: 1, value: 3 });
  assert.equal(extremeBy([NaN, Infinity], v => v, 'max'), null);
  assert.equal(extremeBy([NaN, NaN], v => v, 'min'), null);
});
test('quantile and median copy and filter input while runs stay contiguous', () => {
  const values = [5, 1, 3, 2, 4, NaN];
  assert.equal(quantile(values, .1), 1);
  assert.equal(quantile(values, .5), 3);
  assert.equal(quantile(values, -1), 1);
  assert.equal(quantile(values, 2), 5);
  assert.equal(quantile([], .5), null);
  assert.equal(median(values), 3);
  assert.equal(median([4, 1, 2, 3]), 2.5);
  assert.equal(median([]), null);
  assert.deepEqual(values, [5, 1, 3, 2, 4, NaN]);
  assert.equal(longestRun([1, 0, 0, 1, 0, 0, 0], v => v === 0), 3);
  assert.equal(longestRun([], () => true), 0);
});
test('spending extremes and floor runs treat rounding ties consistently', () => {
  const values = [40, 38, 22.000000000000004, 22, 22.000000000000007, 25];
  const p = profile(values);
  assert.equal(p.floorFirstIndex, 2);
  assert.equal(p.floorHeldYears, 3);
  assert.equal(p.ceiling, 40);
  assert.equal(p.ceilingIndex, 0);
  assert.equal(p.deepestCutIndex, 2);
  close(p.deepestCut, .45);
  assert.equal(p.deliveredMinIndex, 2);
  assert.equal(p.pathLength, 6);
  assert.equal(p.startYear, 2000);
  assert.equal(p.floorRatio, p.floor / 40);
  assert.ok(Object.isFrozen(p));
  assert.ok(Object.isFrozen(p.path));
  values[0] = 1;
  assert.equal(p.path[0], 40);
  assert.equal(profile([30, 20, 20, 25, 20, 20, 20]).floorHeldYears, 3);
});
test('failure keeps the partial year distinct from subsequent unfunded years', () => {
  const p = profile([40, 40, 13], { failed: true, horizon: 5 });
  assert.deepEqual(p.path, [40, 40, 13, 0, 0]);
  assert.equal(p.unfundedYears, 2);
  assert.equal(p.floor, 0);
  assert.equal(p.floorFirstIndex, 2);
  assert.equal(p.floorHeldYears, 2);
  assert.equal(p.lastPartial, 13);
  assert.equal(p.failureIndex, 2);
  assert.equal(p.fundedFloor, 40);
  assert.equal(p.deepestCut, 1);
  assert.equal(p.deepestCutIndex, 2);
  assert.equal(p.deliveredMin, 13);
  assert.equal(p.deliveredMinIndex, 2);
  assert.equal(p.total, 93);
  assert.equal(p.average, 18.6);
  assert.equal(p.median, 13);
  const final = profile([40, 40, 13], { failed: true });
  assert.equal(final.unfundedYears, 0);
  assert.equal(final.floorFirstIndex, 2);
  assert.equal(final.floor, 0);
  assert.equal(final.floorHeldYears, 0);
  assert.equal(final.lastPartial, 13);
  const first = profile([13], { failed: true, horizon: 3 });
  assert.equal(first.fundedFloor, null);
  assert.equal(first.lastPartial, 13);
  assert.equal(first.floor, 0);
  assert.deepEqual(first.path, [13, 0, 0]);
});
test('partial and empty profiles never invent observed spending', () => {
  const p = profile([40, 35, 30], { partial: true, horizon: 30 });
  assert.deepEqual(p.path, [40, 35, 30]);
  assert.equal(p.unfundedYears, 0);
  assert.equal(p.partial, true);
  assert.equal(p.failureIndex, null);
  assert.equal(p.lastPartial, null);
  const empty = profile([], { baseline: 0 });
  for (const key of ['floor', 'median', 'average', 'ceiling', 'floorRatio', 'ceilingRatio', 'fundedFloor', 'deliveredMin', 'deepestCut']) assert.equal(empty[key], null, key);
  assert.equal(empty.floorHeldYears, 0);
  assert.equal(empty.floorFirstIndex, null);
  assert.equal(empty.total, 0);
});
test('need profiles count meaningful shortfalls and contiguous runs', () => {
  const p = profile([40, 35, 30, 36, 20]);
  const need = needProfile(p, 36);
  assert.ok(Object.isFrozen(need));
  assert.equal(need.need, 36);
  assert.equal(need.needRatio, .9);
  assert.equal(need.yearsBelow, 3);
  assert.equal(need.fractionBelow, .6);
  assert.equal(need.longestBelowRun, 2);
  close(need.shortfallYears, .575);
  for (const invalid of [null, undefined, NaN, Infinity, -1]) assert.equal(needProfile(p, invalid), null);
  assert.equal(needProfile(profile([36 - Number.EPSILON * 8]), 36).yearsBelow, 0);
  const zeroProfile = profile([0, 1, 0], { baseline: 0 });
  assert.equal(zeroProfile.floorRatio, null);
  const zero = needProfile(zeroProfile, 1);
  assert.equal(zero.needRatio, null);
  assert.equal(zero.shortfallYears, null);
  assert.equal(zero.yearsBelow, 2);
  const empty = needProfile(profile([]), 1);
  assert.equal(empty.fractionBelow, null);
  assert.equal(empty.longestBelowRun, 0);
});
test('need resolution preserves dollars and recomputes percent from the live baseline', () => {
  assert.equal(resolveNeed({ anchor: 'percent', ratio: .9 }, 40000), 36000);
  assert.equal(resolveNeed({ anchor: 'dollars', amount: 30000 }, 0), 30000);
  assert.equal(resolveNeed({ anchor: 'percent', ratio: .9 }, 0), null);
  assert.equal(resolveNeed(null, 40000), null);
  assert.equal(resolveNeed({ anchor: 'dollars', amount: 0 }, 40000), 0);
  for (const invalid of [-1, NaN, Infinity, '3']) {
    assert.equal(resolveNeed({ anchor: 'dollars', amount: invalid }, 40000), null);
    assert.equal(resolveNeed({ anchor: 'percent', ratio: invalid }, 40000), null);
  }
});
test('browser consumers report a clear missing statistics dependency', () => {
  const engine = fs.readFileSync(require.resolve('../engine.js'), 'utf8');
  assert.throws(() => vm.runInContext(engine, vm.createContext({})), /engine.js requires stats.js/);
  const views = fs.readFileSync(require.resolve('../views.js'), 'utf8');
  const context = vm.createContext({});
  vm.runInContext(fs.readFileSync(require.resolve('../format.js'), 'utf8'), context);
  assert.throws(() => vm.runInContext(views, context), /views.js requires stats.js/);
  vm.runInContext(fs.readFileSync(require.resolve('../stats.js'), 'utf8'), context);
  vm.runInContext(views, context);
  assert.equal(typeof context.MarketAtlasViews.summarizeSweep, 'function');
  assert.equal(context.MarketAtlasViews.median, undefined);
});
